export class MotorRiskDetail {
MotorRiskCode: number;
AssortedCode: string;
MotorRiskSerial: number;
CreatedDate: string;
EffectiveDate: string;
ExpiryDate: string;
IssueDate: string;
PolicyDate: string;
VehicleMakeCode: string;
VehicleCode: string;
VehicleModel: number;
RatingFactorCode: number;
UpdatedValue: number;
PreviousValue: number;
Rate: number;
NetContribution: number;
Mileage: number;
ColorCode: number;
RegistrationNumber: string;
EngineNumber: string;
ChasisNumber: string;
VehicleTypeCode: number;
CertTypeCode: number;
TakafulTypeCode: number;
ParticipantName: string;
ParticipantAddress: string;
CityCode: number;
DistrictCode: number;
CnicNumber: string;
BirthDate: string;
GenderCode: number;
MobileNumber: string;
ResNumber: string;
OfficeNumber: string;
EmailAddress: string;
Remarks: string;
PoDate: string;
PoNumber: string;
Tenure: number;
VeodCode: number;
CommisionRate: number;
IsActive: number;
IsCanceled: number;
CancelDate: string;
Deductible: number;
ContractMatDate: string;
PreviousMotorRiskCode: number;
ProductCode: string;
BranchCode : string;
DocTypeCode : string;
DocNo : number;
DocYear : number;
DocMonth : string;
CancelBy : string;
IsCancelled : number;
ClassCode : string;
GenerateAgainst : string;
TmsAssortedCode : string;
TmsGenerateAgainst : string;
DocString :  string;
CreatedBy : string;
PostBy: string;
PostDate : string;
ClientCode : string;
AgencyCode : string;
PolicyTypeCode : string;
CertificateCode : string;
IsRenewCode : string;
CalcTypeCode : string;
OpenPolAssortedCode : string;



}
